import { TimelineProject, TimelineSection, TimelineTrack, TrackType } from "../../types/timeline"

export const createMockTimelineProject = (): TimelineProject => ({
  id: "project-1",
  name: "Test Project",
  duration: 300,
  fps: 30,
  sampleRate: 48000,
  sections: [
    {
      id: "section-1",
      index: 0,
      name: "Main Section",
      startTime: 0,
      endTime: 300,
      duration: 300,
      isCollapsed: false,
      tracks: [
        {
          id: "track-1",
          type: "video" as TrackType,
          order: 0,
          height: 100,
          name: "Video Track 1",
          clips: [],
          isHidden: false,
          isLocked: false,
          isMuted: false,
          isSolo: false,
          volume: 1,
          pan: 0,
          trackEffects: [],
          trackFilters: [],
        },
        {
          id: "track-2",
          type: "audio" as TrackType,
          order: 1,
          height: 80,
          name: "Audio Track 1",
          clips: [],
          isHidden: false,
          isLocked: false,
          isMuted: false,
          isSolo: false,
          volume: 1,
          pan: 0,
          trackEffects: [],
          trackFilters: [],
        },
      ],
    },
  ],
  globalTracks: [
    {
      id: "global-track-1",
      type: "audio" as TrackType,
      order: 0,
      height: 80,
      name: "Master Audio",
      clips: [],
      isHidden: false,
      isLocked: false,
      isMuted: false,
      isSolo: false,
      volume: 1,
      pan: 0,
      trackEffects: [],
      trackFilters: [],
    },
  ],
  markers: [],
  resources: {
    effects: [],
    filters: [],
    transitions: [],
    templates: [],
    styleTemplates: [],
    subtitleStyles: [],
    music: [],
    media: [],
  },
  settings: {
    resolution: { width: 1920, height: 1080 },
    fps: 30,
    aspectRatio: "16:9",
    sampleRate: 48000,
    channels: 2,
    bitDepth: 16,
    timeFormat: "timecode",
    snapToGrid: true,
    gridSize: 1,
    autoSave: true,
    autoSaveInterval: 300,
  },
  createdAt: new Date(),
  updatedAt: new Date(),
  version: "1.0.0",
})

export const createMockTimelineSection = (): TimelineSection => ({
  id: "section-1",
  index: 0,
  name: "Test Section",
  startTime: 0,
  endTime: 100,
  duration: 100,
  isCollapsed: false,
  tracks: [],
})

export const createMockTimelineTrack = (type: TrackType = "video"): TimelineTrack => ({
  id: `track-${Date.now()}`,
  type,
  order: 0,
  height: type === "video" ? 100 : 80,
  name: `${type} Track`,
  clips: [],
  isHidden: false,
  isLocked: false,
  isMuted: false,
  isSolo: false,
  volume: 1,
  pan: 0,
  trackEffects: [],
  trackFilters: [],
})