use tauri::{Builder, Runtime};

/// Build Tauri application with all registered commands
pub fn build_app<R: Runtime>() -> Builder<R> {
  Builder::<R>::new().invoke_handler(tauri::generate_handler![
    // Language commands
    crate::language_tauri::get_app_language_tauri,
    crate::language_tauri::set_app_language_tauri,
    // Filesystem commands
    crate::filesystem::file_exists,
    crate::filesystem::get_file_stats,
    crate::filesystem::get_platform,
    crate::filesystem::search_files_by_name,
    crate::filesystem::get_absolute_path,
    // App directories commands
    crate::app_dirs::create_app_directories,
    crate::app_dirs::get_app_directories,
    crate::app_dirs::get_directory_sizes,
    crate::app_dirs::clear_app_cache,
    // Media commands
    crate::media::commands::get_media_files,
    crate::media::commands::get_media_metadata,
    crate::media::commands::clear_media_preview_data,
    crate::media::commands::extract_recognition_frames,
    crate::media::commands::generate_media_thumbnail,
    crate::media::commands::generate_timeline_previews,
    crate::media::commands::get_files_with_previews,
    crate::media::commands::get_media_preview_data,
    crate::media::commands::get_timeline_frames,
    crate::media::commands::load_preview_data,
    crate::media::commands::process_media_file_simple,
    crate::media::commands::save_preview_data,
    crate::media::commands::save_timeline_frames,
    // Recognition commands
    crate::recognition::commands::clear_recognition_results,
    crate::recognition::commands::export_recognition_results,
    crate::recognition::commands::get_preview_data_with_recognition,
    crate::recognition::commands::get_recognition_results,
    crate::recognition::commands::get_yolo_class_names,
    crate::recognition::commands::load_yolo_model,
    crate::recognition::commands::process_video_batch,
    crate::recognition::commands::process_video_recognition,
    crate::recognition::commands::process_yolo_batch,
    crate::recognition::commands::set_yolo_target_classes,
    // New YOLO processor commands
    crate::recognition::commands::yolo_commands::create_yolo_processor,
    crate::recognition::commands::yolo_commands::process_image_with_yolo,
    crate::recognition::commands::yolo_commands::process_video_file_with_yolo,
    crate::recognition::commands::yolo_commands::process_image_sequence_with_yolo,
    crate::recognition::commands::yolo_commands::save_yolo_results,
    crate::recognition::commands::yolo_commands::update_yolo_config,
    crate::recognition::commands::yolo_commands::get_yolo_config,
    crate::recognition::commands::yolo_commands::extract_frames_for_yolo,
    crate::recognition::commands::yolo_commands::get_available_yolo_models,
    crate::recognition::commands::yolo_commands::remove_yolo_processor,
    crate::recognition::commands::yolo_commands::list_active_yolo_processors,
    crate::recognition::commands::yolo_commands::cleanup_yolo_processors,
    crate::recognition::commands::yolo_commands::create_yolo_processor_with_builder,
    // Security commands
    crate::security::save_simple_api_key,
    crate::security::save_oauth_credentials,
    crate::security::get_api_key_info,
    crate::security::get_decrypted_api_key,
    crate::security::list_api_keys,
    crate::security::delete_api_key,
    crate::security::validate_api_key,
    crate::security::generate_oauth_url,
    crate::security::exchange_oauth_code,
    crate::security::refresh_oauth_token,
    crate::security::get_oauth_user_info,
    crate::security::parse_oauth_callback_url,
    crate::security::import_from_env,
    crate::security::export_to_env_format,
    // Video compiler commands - using the already exported commands from the module
    crate::video_compiler::commands::auto_select_gpu,
    crate::video_compiler::commands::benchmark_gpu,
    crate::video_compiler::commands::check_gpu_encoder_availability,
    crate::video_compiler::commands::check_hardware_acceleration,
    crate::video_compiler::commands::check_hardware_acceleration_support,
    crate::video_compiler::commands::cache_media_metadata,
    crate::video_compiler::commands::clean_old_cache,
    crate::video_compiler::commands::cleanup_cache,
    crate::video_compiler::commands::clear_all_cache,
    crate::video_compiler::commands::clear_cache,
    crate::video_compiler::commands::clear_file_preview_cache,
    crate::video_compiler::commands::clear_frame_cache,
    crate::video_compiler::commands::clear_media_metadata_cache,
    crate::video_compiler::commands::clear_prerender_cache,
    crate::video_compiler::commands::clear_preview_cache,
    crate::video_compiler::commands::clear_preview_cache_for_file,
    crate::video_compiler::commands::clear_preview_generator_cache_for_file,
    crate::video_compiler::commands::clear_project_cache,
    crate::video_compiler::commands::clear_project_previews,
    crate::video_compiler::commands::clear_render_cache,
    crate::video_compiler::commands::compile_video,
    crate::video_compiler::commands::cancel_render,
    crate::video_compiler::commands::build_preview_command,
    crate::video_compiler::commands::build_prerender_segment_command,
    crate::video_compiler::commands::build_render_command_with_settings,
    crate::video_compiler::commands::build_segment_render_command,
    crate::video_compiler::commands::create_new_project,
    crate::video_compiler::commands::analyze_project,
    crate::video_compiler::commands::backup_project,
    crate::video_compiler::commands::check_project_media_availability,
    crate::video_compiler::commands::batch_generate_previews_service,
    crate::video_compiler::commands::apply_quality_preset,
    crate::video_compiler::commands::apply_video_filter,
    crate::video_compiler::commands::check_ffmpeg_available,
    crate::video_compiler::commands::check_ffmpeg_capabilities,
    crate::video_compiler::commands::check_ffmpeg_installation,
    crate::video_compiler::commands::check_render_job_timeouts,
    crate::video_compiler::commands::concat_videos,
    crate::video_compiler::commands::configure_cache,
    crate::video_compiler::commands::add_clip_to_track,
    crate::video_compiler::commands::add_subtitles_to_project,
    crate::video_compiler::commands::create_clip,
    crate::video_compiler::commands::create_custom_alert,
    crate::video_compiler::commands::create_effect,
    crate::video_compiler::commands::create_filter,
    crate::video_compiler::commands::create_schema_objects,
    crate::video_compiler::commands::create_style_template,
    // Pipeline commands
    crate::video_compiler::commands::create_and_execute_pipeline,
    crate::video_compiler::commands::get_pipeline_info,
    crate::video_compiler::commands::cancel_pipeline,
    crate::video_compiler::commands::get_pipeline_statistics,
    crate::video_compiler::commands::get_pipeline_context,
    crate::video_compiler::commands::update_pipeline_settings,
    crate::video_compiler::commands::validate_pipeline_configuration,
    crate::video_compiler::commands::insert_pipeline_stage,
    crate::video_compiler::commands::remove_pipeline_stage,
    crate::video_compiler::commands::build_custom_pipeline,
    crate::video_compiler::commands::get_pipeline_execution_summary,
    crate::video_compiler::commands::get_pipeline_progress,
    crate::video_compiler::commands::cleanup_completed_pipelines,
    // Monitoring commands
    crate::video_compiler::commands::get_service_metrics_summary,
    crate::video_compiler::commands::reset_service_metrics_detailed,
    crate::video_compiler::commands::get_all_metrics_summaries,
    crate::video_compiler::commands::export_metrics_prometheus_detailed,
    crate::video_compiler::commands::check_services_health,
    crate::video_compiler::commands::get_performance_metrics,
    crate::video_compiler::commands::reset_all_metrics,
    // Video analysis commands
    crate::video_compiler::commands::ffmpeg_get_metadata,
    crate::video_compiler::commands::ffmpeg_detect_scenes,
    crate::video_compiler::commands::ffmpeg_analyze_quality,
    crate::video_compiler::commands::ffmpeg_detect_silence,
    crate::video_compiler::commands::ffmpeg_analyze_motion,
    crate::video_compiler::commands::ffmpeg_extract_keyframes,
    crate::video_compiler::commands::ffmpeg_analyze_audio,
    crate::video_compiler::commands::ffmpeg_quick_analysis,
    // Whisper commands
    crate::video_compiler::commands::whisper_transcribe_openai,
    crate::video_compiler::commands::whisper_translate_openai,
    crate::video_compiler::commands::whisper_transcribe_local,
    crate::video_compiler::commands::whisper_get_local_models,
    crate::video_compiler::commands::whisper_download_model,
    crate::video_compiler::commands::whisper_check_local_availability,
    crate::video_compiler::commands::extract_audio_for_whisper,
    // Batch processing commands
    crate::video_compiler::commands::create_batch_job,
    crate::video_compiler::commands::get_batch_job_info,
    crate::video_compiler::commands::cancel_batch_job,
    crate::video_compiler::commands::list_batch_jobs,
    crate::video_compiler::commands::get_batch_processing_stats,
    crate::video_compiler::commands::update_batch_clip_result,
    crate::video_compiler::commands::cleanup_batch_jobs,
    crate::video_compiler::commands::set_batch_job_status,
    // Multimodal analysis commands
    crate::video_compiler::commands::extract_frames_for_multimodal_analysis,
    crate::video_compiler::commands::convert_image_to_base64,
    crate::video_compiler::commands::extract_thumbnail_candidates,
    crate::video_compiler::commands::create_frame_collage,
    crate::video_compiler::commands::optimize_image_for_analysis,
    crate::video_compiler::commands::cleanup_extracted_frames,
    // Platform optimization commands
    crate::video_compiler::commands::ffmpeg_optimize_for_platform,
    crate::video_compiler::commands::ffmpeg_generate_platform_thumbnail,
    crate::video_compiler::commands::ffmpeg_batch_optimize_platforms,
    crate::video_compiler::commands::ffmpeg_analyze_platform_compliance,
    crate::video_compiler::commands::ffmpeg_create_progressive_video,
    // Workflow automation commands
    crate::video_compiler::commands::create_directory,
    crate::video_compiler::commands::create_timeline_project,
    crate::video_compiler::commands::compile_workflow_video,
    crate::video_compiler::commands::analyze_workflow_video_quality,
    crate::video_compiler::commands::create_workflow_preview,
    crate::video_compiler::commands::cleanup_workflow_temp_files,
    // Misc commands
    crate::greet,
    crate::scan_media_folder,
    crate::scan_media_folder_with_thumbnails,
  ])
}
