name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libavfilter-dev \
            libavdevice-dev \
            libswscale-dev \
            libswresample-dev \
            pkg-config \
            clang \
            llvm-dev \
            libclang-dev
          
          # Verify headers and set environment variables
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS=-I/usr/include" >> $GITHUB_ENV
          
          # Check if headers exist
          if [ ! -f "/usr/include/libswscale/swscale.h" ]; then
            echo "Installing additional FFmpeg packages..."
            sudo apt-get install -y $(apt-cache search libswscale | grep -E '^libswscale[0-9]+-dev' | cut -d' ' -f1) || true
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci --cache clean --force

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm run test
