name: Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libavfilter-dev \
            libavdevice-dev \
            libswscale-dev \
            libswresample-dev \
            pkg-config \
            clang \
            llvm-dev \
            libclang-dev
          
          # Run the setup script to handle configuration
          chmod +x scripts/setup-ffmpeg-linux.sh
          ./scripts/setup-ffmpeg-linux.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci --cache clean --force

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm run test
