name: Bundle Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bundle-analysis:
    name: Analyze Bundle Size
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm config set fetch-timeout 300000
          npm config set fetch-retries 5
          npm ci --prefer-offline --no-audit --no-fund
          
      - name: Build with bundle analysis
        run: npm run build:analyze
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CI: true
          NODE_ENV: production
          
      - name: List generated files for debugging
        run: |
          echo "Contents of dist directory:"
          find dist -name "*.json" -o -name "*.xml" -o -name "*bundle*" -o -name "*.map" | head -20
          echo "Contents of .next directory:"
          find .next -name "*.json" -o -name "*.xml" -o -name "*bundle*" 2>/dev/null | head -10 || echo ".next directory not found"
          echo "Root directory stats files:"
          find . -maxdepth 1 -name "*stats*" -o -name "*bundle*" -o -name "*analyze*" | head -10
          echo "Webpack stats file search:"
          find . -name "webpack-stats.json" -o -name "build-stats.json" -o -name "stats.json" | head -10
          
      - name: Generate simple bundle stats
        run: |
          echo "Generating basic bundle analysis..."
          echo '{"bundleSize": "Generated during build", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > bundle-stats.json
          if [ -d "dist" ]; then
            du -sh dist/* > dist-sizes.txt || echo "No files in dist"
            echo "Bundle sizes:" >> bundle-stats.json
            cat dist-sizes.txt >> bundle-stats.json || echo "No size data available"
          fi
          
      # Bundle analysis disabled - not properly configured
      # To enable bundle analysis, install @codecov/bundler-plugin
      # and configure it properly with webpack/vite/rollup
      # - name: Upload bundle stats to Codecov
      #   if: always()
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     name: bundle-analysis
      #     flags: bundle
      #     files: bundle-stats.json,dist-sizes.txt
      #     fail_ci_if_error: false
      #     verbose: true