# Alternative JS linting workflow using Bun for better Windows performance

name: Lint Node.js (Bun)

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "src-tauri/**"
      - "README.md"

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Disable git core.autocrlf on Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile

      - name: Run lint step
        run: bun run lint

      - name: Check import order
        run: bun run format:imports

      - name: Run TypeScript check
        run: bun run typecheck || echo "TypeScript check not configured"

      - name: Run tests
        run: bun run test