name: Quick Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libavfilter-dev \
            libavdevice-dev \
            libswscale-dev \
            libswresample-dev \
            pkg-config \
            libglib2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev
            
      - name: Setup FFmpeg for Linux
        run: |
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_SYSTEM_LIBS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1" >> $GITHUB_ENV
          
          # Set FFmpeg environment variables explicitly
          echo "FFMPEG_DIR=/usr" >> $GITHUB_ENV
          echo "FFMPEG_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "FFMPEG_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "FFMPEG_AVCODEC_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "FFMPEG_AVFORMAT_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "FFMPEG_AVUTIL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "FFMPEG_AVDEVICE_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "FFMPEG_AVFILTER_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "FFMPEG_SWSCALE_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          echo "FFMPEG_SWRESAMPLE_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
          
          # Try main FFmpeg setup script
          if ! bash scripts/setup-ffmpeg-linux.sh; then
              echo "Main setup failed, trying pkg-config approach..."
              bash scripts/setup-ffmpeg-pkg-config.sh
          fi
          
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ubuntu-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install frontend dependencies
        run: bun install
        
      - name: Frontend lint check
        run: bun run lint
        
      - name: Backend format check
        working-directory: src-tauri
        run: cargo fmt -- --check
        
      - name: Create dist directory for tauri context
        run: mkdir -p dist
        
      - name: Backend clippy check
        working-directory: src-tauri
        run: cargo clippy --lib -- -D warnings
        
      - name: Quick backend test (core modules only)
        working-directory: src-tauri
        run: |
          # Run only critical backend tests to catch major issues quickly
          cargo test --lib language_tauri::tests -- --test-threads=1
          cargo test --lib command_registry::tests -- --test-threads=1
          cargo test --lib core::di::tests -- --test-threads=1