name: Test and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  frontend-test-coverage:
    name: Frontend Tests & Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create test results directory
        run: mkdir -p test-results

      - name: Run tests with coverage
        run: bun run test:coverage
        env:
          CI: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test-results/junit.xml
          flags: frontend
          name: frontend-tests
          fail_ci_if_error: false

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false
          slug: chatman-media/timeline-studio

  rust-test-coverage:
    name: Rust Tests & Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          
          # Install base dependencies
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libglib2.0-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libsoup-3.0-dev \
            libjavascriptcoregtk-4.1-dev \
            pkg-config \
            build-essential \
            clang \
            llvm-dev \
            libclang-dev

      - name: Setup FFmpeg
        run: |
          # Install FFmpeg packages first
          sudo apt-get install -y \
            ffmpeg \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libavfilter-dev \
            libavdevice-dev \
            libswscale-dev \
            libswresample-dev
          
          # Run the setup script to handle any configuration issues
          chmod +x scripts/setup-ffmpeg-linux.sh
          ./scripts/setup-ffmpeg-linux.sh

      - name: Install ONNX Runtime
        run: |
          wget https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-linux-x64-1.22.0.tgz
          tar -xzf onnxruntime-linux-x64-1.22.0.tgz
          sudo cp onnxruntime-linux-x64-1.22.0/lib/*.so* /usr/local/lib/
          sudo ldconfig
          echo "ORT_DYLIB_PATH=/usr/local/lib/libonnxruntime.so" >> $GITHUB_ENV

      - name: Install cargo-llvm-cov
        run: |
          if ! command -v cargo-llvm-cov &> /dev/null; then
            cargo install cargo-llvm-cov --locked
          fi

      - name: Create dist directory
        run: mkdir -p dist

      - name: Run Rust tests with coverage
        run: |
          cd src-tauri
          
          # Find LLVM path dynamically for clang
          LLVM_PATHS=(
            "/usr/lib/llvm-18/lib"
            "/usr/lib/llvm-17/lib" 
            "/usr/lib/llvm-16/lib"
            "/usr/lib/llvm-15/lib"
            "/usr/lib/llvm-14/lib"
            "/usr/lib/llvm-13/lib"
            "/usr/lib/x86_64-linux-gnu"
          )
          
          for path in "${LLVM_PATHS[@]}"; do
            if [ -d "$path" ] && [ -f "$path/libclang.so" -o -f "$path/libclang.so.1" ]; then
              export LIBCLANG_PATH="$path"
              echo "✅ Found LIBCLANG_PATH: $path"
              break
            fi
          done
          
          # Debug FFmpeg detection before building
          echo "=== Debug before Rust build ==="
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          echo "LIBCLANG_PATH: $LIBCLANG_PATH"
          
          # Test that FFmpeg libraries can be found
          pkg-config --exists libswscale && echo "✅ libswscale detected" || echo "❌ libswscale NOT detected"
          pkg-config --exists libavcodec && echo "✅ libavcodec detected" || echo "❌ libavcodec NOT detected"
          
          # Run the actual build
          cargo llvm-cov --lcov --output-path coverage.info

      - name: Check test results
        run: |
          cd src-tauri
          if [ -f coverage.info ]; then
            echo "✅ Coverage report generated successfully"
          else
            echo "❌ Coverage report not generated"
            exit 1
          fi

      - name: Upload Rust coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./src-tauri/coverage.info
          flags: rust
          name: rust-coverage
          fail_ci_if_error: false
          slug: chatman-media/timeline-studio

